name: Continuous Integration

on:
  push:
    branches:
      - "trunk"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "trunk"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Statcheck test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make chocolate-doom python3 python3-yaml

      - name: Run checks
        run: |
          make check
