name: Continuous Integration

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Statcheck test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make chocolate-doom python3 python3-yaml

      - name: Patch out broken demos
        run: |
          # These work in Chocolate Doom HEAD but don't seem to currently
          # work in the older version in ubuntu-latest.
          # TODO: Reenable these.
          grep -v 30av-25337 < demos.txt | grep -v pl2all1.txt > new-demos.txt
          mv new-demos.txt demos.txt

      - name: Run checks
        run: |
          make check
